### ISSUE TITLE
Leaf Auth Not Working

### ISSUE THREAD

**Issue by matthewjamesr** [leafsphp/auth#1]
@mychidarko Hello again. This time, I cannot get `\Leaf\Auth` helpers to work.

I have generated login logic via `php leaf scaffold:auth` and that worked.

Below is the error output:

```
Fatal error: Uncaught Error: Call to undefined method Leaf\Auth::guard() in C:\Users\me\OneDrive\Documents\dev\PHP\glint\app\controllers\Auth\LoginController.php:12 Stack trace: #0 [internal function]: App\Controllers\Auth\LoginController->show() leafsphp/leafMVC#1 C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\leafs\router\src\Router\Core.php(451): call_user_func_array(Array, Array) leafsphp/leafMVC#2 C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\leafs\router\src\Router\Core.php(417): Leaf\Router\Core::invoke('\\App\\Controller...', Array) leafsphp/leafMVC#3 C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\leafs\router\src\Router\Core.php(349): Leaf\Router\Core::handle(Array, true) leafsphp/leafMVC#4 C:\Users\me\OneDrive\Documents\dev\PHP\glint\public\index.php(130): Leaf\Router\Core::run() leafsphp/leafMVC#5 C:\Users\me\OneDrive\Documents\dev\PHP\glint\index.php(24): require_once('C:\\Users\\me\\One...') leafsphp/leafMVC#6 {main} thrown in C:\Users\me\OneDrive\Documents\dev\PHP\glint\app\controllers\Auth\LoginController.php on line 12
```

**Comment by matthewjamesr** [comment]
@mychidarko Thanks! I created a new project `leaf create` and the problem is there.

**Comment by mychidarko** [comment]
Yeah. It's a problem stemming from the library rewrite. It'll be fixed shortly. Thanks for the patience.

**Comment by matthewjamesr** [comment]
All good! I am happy to support you/leaf by working with it and bringing these issues forward.

Side-note: Joined Discord to talk about some features!

**Comment by matthewjamesr** [comment]
@mychidarko Do you have any updates on resolving? I see active merges, I assume you are working on meshing the changes into LeafMVC?

I am basically ready to launch my MVP pending working Auth. Thanks!

**Comment by mychidarko** [comment]
Hi @matthewjamesr final updates will be pushed soon. Thanks for the patience 🙏🏽

**Comment by mychidarko** [comment]
Hi @matthewjamesr. Your issue has finally been fixed. I took the liberty of rewriting the whole library. It is now based on leaf db v2 which supports MySQL, PGSQL and other databases. It is faster and easier to use and comes with new features as well. The guide is being updated, but for now, there's almost no difference between v2's syntax and the one in the guide.

You can find the mini changelog [here](https://github.com/leafsphp/auth/releases/tag/v2.0).

To get rid of this problem in an existing project, you can run

```sh
composer require leafs/auth -W
```

**Comment by matthewjamesr** [comment]
This does not seem to fix an install using the auth scaffold.

Type: ErrorException
Code: 8192
Message: Non-static method Leaf\Auth\Core::autoConnect() should not be called statically
File: C:\xampp\htdocs\glint\app\controllers\Controller.php
Line: 23

**Comment by matthewjamesr** [comment]
@mychidarko I got it to work by using functional mode for some reason.

```auth()->autoConnect();```

**Comment by matthewjamesr** [comment]
Autoconnect nor connect seem to work.

```
Type: ErrorException
Code: 1024
Message: You need to connect to your database first
File: C:\xampp\htdocs\glint\vendor\leafs\auth\src\Auth\Core.php
Line: 122
```

```
#0 [internal function]: Leaf\Exception\General::handleErrors(1024, 'You need to con...', 'C:\\xampp\\htdocs...', 122, Array)
#1 C:\xampp\htdocs\glint\vendor\leafs\auth\src\Auth\Core.php(122): trigger_error('You need to con...')
#2 C:\xampp\htdocs\glint\vendor\leafs\auth\src\Auth.php(130): Leaf\Auth\Core::leafDbConnect()
#3 C:\xampp\htdocs\glint\app\controllers\Auth\RegisterController.php(33): Leaf\Auth::register('users', Array, Array)
#4 [internal function]: App\Controllers\Auth\RegisterController->store()
#5 C:\xampp\htdocs\glint\vendor\leafs\router\src\Router\Core.php(451): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\glint\vendor\leafs\router\src\Router\Core.php(417): Leaf\Router\Core::invoke('\\App\\Controller...', Array)
#7 C:\xampp\htdocs\glint\vendor\leafs\router\src\Router\Core.php(349): Leaf\Router\Core::handle(Array, true)
#8 C:\xampp\htdocs\glint\public\index.php(130): Leaf\Router\Core::run()
#9 {main}
```

**Comment by matthewjamesr** [comment]
I think it is actually connect, and throwing an error for some other reason.

**Comment by mychidarko** [comment]
> This does not seem to fix an install using the auth scaffold.
> 
> 
> 
> Type: ErrorException
> 
> Code: 8192
> 
> Message: Non-static method Leaf\Auth\Core::autoConnect() should not be called statically
> 
> File: C:\xampp\htdocs\glint\app\controllers\Controller.php
> 
> Line: 23

Oh yeah, this is s as documentation problem. Pls use all the methods on the Auth class, not Auth\Core.

The documentation is being updated

**Comment by mychidarko** [comment]
> actually connect, and throwing an error for some other reason.

Can you pls try checking the normal `connect`

**Comment by matthewjamesr** [comment]
@mychidarko I did try ```auth()->connect()``` with the needed arguments included, no fix. I will try more when I get home tonight. Perhaps the scaffold:auth controllers need to be updated for the re-write? I can take a look at that as well.

**Comment by mychidarko** [comment]
Sure, thank you

**Comment by matthewjamesr** [comment]
Yeah, I give up till the docs are updated. 😢

**Comment by matthewjamesr** [comment]
Okkkk so I got a registration to insert:

```db()->connect('127.0.0.1', "glint", "leaf", getenv("DB_PASSWORD"), "mysql");```

Now, it redirect to white page, tons of routing stuff going on but that is easy view/scaffolding stuff I suspect.

**Comment by mychidarko** [comment]
You can set the redirect page by configuring `GUARD_HOME`

That part is covered in the current docs

**Comment by matthewjamesr** [comment]
Setting ```GUARD_HOME``` from config\auth.php does not work, had to set using functional mode. I now have fully working authentication, had to make a few changes to get it going.
