### ISSUE TITLE
Undefined array key \"id\"

### ISSUE THREAD

**Issue by kofesto** [leafsphp/auth#10]
**Undefined array key \"id\"**
I keep getting this error `Undefined array key \"id\` each time I login,
here is my login 
`
auth()->login([
                    'email'=>$user->email,
                    'password'=>$user->password
                   ])`
If i fetched the user details normally it will come out but login keep giving error, I just need a way i could get JWT token, and forget the login since it's giving error

**Comment by mychidarko** [comment]
This issue pops up when the `PRIMARY KEY` for the table you're trying to access isn't `id`.

To get rid of this issue, you need to change Leaf Auth's default `DB_TABLE` to whatever your table's PRIMARY KEY is. Your code will look something like this:

```php
auth()->config('ID_KEY', 'user_id');
```
