### ISSUE TITLE
Register function always return null

### ISSUE THREAD

**Issue by Feka7** [leafsphp/auth#12]
**Describe the bug**
Register function always return null also if the user is registered correctly.

**To Reproduce**
1. Install leaf with leaf CLI: leaf create "your_project", preset leaf, version v3, no tests
2. Run leaf install db
3. Run leaf install auth
4.  Add the following code in index.php

```
<?php

require __DIR__ . '/vendor/autoload.php';

db()->connect([
	'host' => '127.0.0.1',
	'username' => 'root',
	'password' => '',
	'dbname' => 'leaf',
]);

app()->get('/', function () {
	response()->page('./welcome.html');
});

app()->get('/register', function () {
	$user = auth()->register([
		'username' => 'mike',
		'password' => 'mypass'
	]);

	if (!$user) {
		response()->exit("User not returned!");
		
		// both two cases below always return an empty array
		// response()->exit(auth()->errors());
		// response()->exit(db()->errors());
	}
	response()->json($user);
});

// Try if user is registered anyway
app()->get('/login', function () {

	$user = auth()->login([
		'username' => 'mike',
		'password' => 'mypass'
	]);

	if (!$user) {
		response()->exit(auth()->errors());
	}

	response()->json($user);
});

app()->run();
```

**Expected behavior**
1. Call the /register endopoint for add the user to your database. It should return the user data but return null.
2. Then call the /login endpoint: user is logged correctly (so the registration in the previous step worked)

**Additional context**
I think the error is here: https://github.com/leafsphp/auth/blob/main/src/Auth.php#L168, return null but shouldn't

DB Table:
```
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(256) NOT NULL,
  `password` varchar(256) NOT NULL,
  `created_at` date DEFAULT NULL,
  `updated_at` date DEFAULT NULL,
  PRIMARY KEY (`id`)
)
```

DB: MySQL 5.7.40
PHP: 7.4.33

**Comment by mychidarko** [comment]
I followed these same steps but was unable to recreate the error. Can you confirm that your db connection was successful?

<img width="722" alt="image" src="https://user-images.githubusercontent.com/26604242/222860813-26336a20-c250-48f6-b8f8-236e170ea7d2.png">

**Comment by mychidarko** [comment]
Although you already did, can you give me some more context to work with?

**Comment by Feka7** [comment]
No worry! I have just found the problem. I used date instead of datetime in my users table, my fault 🙂

**Comment by Feka7** [comment]
For more context I also add the correct implementation of users table:

```
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(256) NOT NULL,
  `password` varchar(256) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
)
```
