### ISSUE TITLE
Add the Auth::$middleware property

### ISSUE THREAD

**Issue by fadrian06** [leafsphp/auth#23]

**Comment by mychidarko** [comment]
Hi @fadrian06 can you pls add some context to this

**Comment by fadrian06** [comment]
There are several references to Auth::$middleware that has not been declared

**Comment by mychidarko** [comment]
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/71e46aca-8d2f-4104-8e92-5fcf8892d5cd">

I just noticed this. It appears to be a deprecated feature, but some references slipped through. It'll be removed in the next auth version. Thanks for the catch!
